package org.formentor.magnolia.ai.infrastructure.openai;


import lombok.Data;

import java.util.List;

/**
 * An object containing a response from the completion api
 *
 * https://beta.openai.com/docs/api-reference/edits/create
 */
@Data
public class EditResult {

    /**
     * The type of object returned, should be "text_completion"
     */
    String object;

    /**
     * The creation time in epoch seconds.
     */
    long created;


    /**
     * A list of generated completions.
     */
    List<CompletionChoice> choices;

    /**
     * The API usage for this request
     */
    Usage usage;

    /**
     * A completion generated by GPT-3
     *
     * https://beta.openai.com/docs/api-reference/edits/create
     */
    @Data
    public static class CompletionChoice {
        /**
         * The generated text. Will include the prompt if {@link EditRequest#} is true
         */
        String text;

        /**
         * This index of this completion in the returned list.
         */
        Integer index;

    }

    /**
     * The OpenAI resources used by a request
     */
    @Data
    public static class Usage {
        /**
         * The number of prompt tokens used.
         */
        long prompt_tokens;

        /**
         * The number of completion tokens used.
         */
        long completion_tokens;

        /**
         * The number of total tokens used
         */
        long total_tokens;
    }
}